---
# 菜单配置初始化(服务启动时会进行数据检查，如果存在则不再初始化)
- name: 首页
  icon: dashboard
  router: "/admin/home"
  sequence: 9
- name: 系统管理
  icon: setting
  sequence: 7
  children:
    - name: 菜单管理
      icon: solution
      router: "/admin/system/menu"
      sequence: 9
    - name: 角色管理
      icon: audit
      router: "/admin/system/role"
      sequence: 8
    - name: 用户管理
      icon: user
      router: "/admin/system/user"
      sequence: 7